name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_OUTPUT: viewer

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Bootstrap Project
        run: tools/bootstrap.sh

      - uses: idleberg/create-playdate-release@809e48f # v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_folder: font_viewer
