name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  BUILD_OUTPUT: viewer

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Bootstrap Project
        run: tools/bootstrap.sh

      - uses: idleberg/create-playdate-release@809e48f0b355e0d7cadfbc7ddf43932dcf9742dc # v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: font_viewer
